### ISSUE TITLE
Problema en el contenedor del slide en el creador de la presentación.

### ISSUE THREAD

**Issue by Xarom23** [gio-gigi/presentation-maker#15]
Hay un problema con el contenedor del slide en la preview ya que al escribir sin saltos de línea, el contenedor aumenta el ancho del contenedor.
![Captura de pantalla (433)](https://github.com/gio-gigi/presentation-maker/assets/111985056/14f4af9e-482d-4c65-8795-a6515db9e690)

**Comment by Lorenzo2345612** [comment]
Se debe de cambiar la linea 

```
flex: 1;
```

por 

```
width: 50%;
```

en los estilos de los componentes presentation_preview y presentation_editor

además de los siguientes estilos en el slide-content:

```
    overflow-wrap: break-word;
    word-wrap: break-word;
    word-break: break-word;
    hyphens: auto;
```
